/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function treeShake(input: string, preset: 'safest' | 'recommended' | 'smallest' | 'disabled', minify: boolean): TreeShakeResultBinding
export declare class TreeShakeResultBinding {
  output: string
  diagnostics: Array<string>
}
