/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function treeShake(input: string, treeShake: string | undefined | null, doMinify: boolean): TreeShakeResultBinding
export declare class TreeShakeResultBinding {
  output: string
  diagnostics: Array<string>
}
