/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function treeShake(input: string, doTreeShake: boolean, doMinify: boolean, evalMode: boolean): TreeShakeResultBinding
export declare class TreeShakeResultBinding {
  output: string
  diagnostics: Array<string>
}
