[package]
name = "kermanx_tree-shaker_napi"
version = "0.0.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/src", "/build.rs"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { workspace = true, features = ["napi4"] }
napi-derive = { workspace = true }
tree_shaker = { workspace = true }
oxc = { workspace = true, features = ["codegen", "semantic", "minifier"] }

[build-dependencies]
napi-build = { workspace = true }
