name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: cargo fix --allow-dirty --allow-staged
      
      - name: Rustfmt
        run: cargo fmt --all

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
